language: node_js
node_js:
- 4.1
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: DPWcfmOdIWImvbeqBlMLF7X7MP9x9GTyo6tWHW/UglL02evGB4oeAROOkNkSE2ylYKigLn1dY+yrMXdTkQxRtVJw+1n/Mzy762O3RsKidC7NQVEvFabRCR9Y3h6mcD3fw6dAD1/5xUiBCyFFBbgWIOdgGuE0JtTMMJ9kRmRAxr8=
  on:
    tags: true
    all_branches: true
